version: '3'


services:
 web:
   build: .
   command: python manage.py runserver 0.0.0.0:8002
   volumes:
     - .:/app
   ports:
     - "8002:8002"  # Map container port 8002 to host port 8002
   depends_on:
     - db  # This ensures that the 'web' service starts after the 'db' service


 db:
   image: postgres:latest
   environment:
     POSTGRES_DB: league
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: puffnane1738
   ports:
     - "5434:5432"  # Map container port 5432 to host port 5433