# Generated by Django 4.2.6 on 2023-10-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='last_match',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
